version: '3.9'

services:
  ctf_backend:
    container_name: ctf_backend
    image: ctf_backend
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    restart: always
    command: sh -c "python3 manage.py migrate && gunicorn Ctf_Project.wsgi:application --workers=1 --bind 0.0.0.0:8080"
    depends_on:
      - ctf_db
    networks:
      - apachee_network
    env_file:
      - ./Ctf_Project/back.env

  ctf_db:
    container_name: ctf_db
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - ctf_db_volume:/var/lib/postgres/data
    networks:
      - apachee_network
    env_file:
      - ./Ctf_Project/db.env

volumes:
  ctf_db_volume:

networks:
  apachee_network:
    driver: bridge
    name: apachee_network